= This is a test

This is a cool test

== PREÁMBULO

Como libertarios, buscamos un mundo de libertad: un mundo en el que todos los individuos sean soberanos sobre sus propias vidas y no se vean obligados a sacrificar sus valores en beneficio de los demás.

Creemos que el respeto de los derechos individuales es la condición previa esencial para un mundo libre y próspero, que la fuerza y ​​el fraude deben ser desterrados de las relaciones humanas, y que solo a través de la libertad se pueden lograr la paz y la prosperidad.

En consecuencia, defendemos el derecho de cada persona a realizar cualquier actividad pacífica y honesta, y acogemos la diversidad que trae la libertad. El mundo que buscamos construir es uno en el que las personas sean libres de seguir sus propios sueños a su manera, sin la interferencia del gobierno o de cualquier poder autoritario.

En las siguientes páginas exponemos nuestros principios básicos y enumeramos varias posturas políticas derivadas de esos principios.

Sin embargo, estas políticas específicas no son nuestro objetivo. Nuestro objetivo es ni más ni menos que un mundo liberado durante nuestra vida, y es con este fin que tomamos estas posiciones.

En cumplimiento de esta misión,  renueva y reitera su compromiso con la estricta observancia de la Constitución y sus leyes, sin aceptar pactos o acuerdos que lo subordinen a alguna organización del exterior; actuando con independencia de entidades o partidos extranjeros, y rechazando cualquier apoyo económico, político o propagandístico provenientes de entes jurídicos prohibidos por la ley. 


== STATEMENT OF PRINCIPLES

We, the members of the Libertarian Party, challenge the cult of the omnipotent state and defend the rights of the individual.

We hold that all individuals have the right to exercise sole dominion over their own lives, and have the right to live in whatever manner they choose, so long as they do not forcibly interfere with the equal right of others to live in whatever manner they choose.

Governments throughout history have regularly operated on the opposite principle, that the State has the right to dispose of the lives of individuals and the fruits of their labor. Even within the United States, all political parties other than our own grant to government the right to regulate the lives of individuals and seize the fruits of their labor without their consent.

We, on the contrary, deny the right of any government to do these things, and hold that where governments exist, they must not violate the rights of any individual: namely, (1) the right to life — accordingly we support the prohibition of the initiation of physical force against others; (2) the right to liberty of speech and action — accordingly we oppose all attempts by government to abridge the freedom of speech and press, as well as government censorship in any form; and (3) the right to property — accordingly we oppose all government interference with private property, such as confiscation, nationalization, and eminent domain, and support the prohibition of robbery, trespass, fraud, and misrepresentation.

Since governments, when instituted, must not violate individual rights, we oppose all interference by government in the areas of voluntary and contractual relations among individuals. People should not be forced to sacrifice their lives and property for the benefit of others. They should be left free by government to deal with one another as free traders; and the resultant economic system, the only one compatible with the protection of individual rights, is the free market.

