____
*FORMATO OC.3 “RA-AS-ES” RECIBO DE APORTACIONES DE AFILIADAS, AFILIADOS
Y SIMPATIZANTES EN ESPECIE*

No. de folio (1): xxxxxxxxxxxxx

Lugar (2): Playas de Rosarito, Baja California

Fecha (3): 25 de agosto de 2020

Bueno por (4) $ xxxxxxxxxxxxxxxxxxxxxxxx

Organización de Ciudadanos (5):
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Acusa Recibo de:

Nombre del aportante (6):
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Domicilio del aportante (7):
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Clave de Elector (8): XXXXXXXXXXXXXXXXXXX R.F.C. (9):
XXXXXXXXXXXXXXXXXXXXXXXXX

Teléfono (10): xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Por la cantidad de (11) $ xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Importe con letra (12):
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Bien aportado (13):
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Criterio de valuación utilizado (14):
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Aportante (15):
____

☐

☐

AFILIADO/A

SIMPATIZANTE

Firma del Aportante (16)

Nombre y Firma de la Persona

Responsable de Finanzas (17)

== INSTRUCTIVO DE LLENADO DEL 

==  FORMATO OC.3 “RA-AS-ES” RECIBO DE APORTACIONES DE AFILIADAS, AFILIADOS Y +
SIMPATIZANTES EN ESPECIE

== 

* Deberá presentarse el formato, de acuerdo con lo siguiente:

____
Claves:
____

[arabic]
. Deberá expresarse el número de recibo expedido.
. Deberá expresar el lugar en el cual se expidió el recibo.
. Deberá expresarse la fecha en la cual el recibo fue expedido o
cancelado (día, mes y año).
. Deberá expresarse el monto de la aportación que ampara.
. Deberá expresar la denominación de la Organización de Ciudadanos.
. Deberá expresar el nombre de la persona quien realizó la aportación,
iniciando por apellido paterno, materno y nombre (s).
. Deberán expresarse el domicilio de la persona quien realizó la
aportación, que deberá contener la calle, número, colonia, ciudad,
entidad federativa y código postal.
. Deberá expresar la clave que describe la credencial para votar con
fotografía de la persona quien realizó la aportación.
. Deberá expresar el Registro Federal de Contribuyentes de la persona
quien realizó la aportación.
. Deberá expresarse el número telefónico de quien realizó la aportación.
. Deberá expresarse el monto en cantidad de la aportación que ampara.
. Deberá expresarse el monto en letra de la aportación que ampara.
. Deberá describirse de forma detallada el bien o bienes aportados.
. Deberá detallar el criterio de valuación que utilizó para valuar los
bienes aportados.
. Deberá señalar el tipo de aportante, si corresponde a una afiliada, a
un afiliado o a un simpatizante.
. Firma autógrafa de quien realizó la aportación.
. Nombre y firma autógrafa de la persona responsable de finanzas.
